# Generated by Django 5.2.7 on 2025-11-13 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_addplace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addplace',
            new_name='place',
        ),
        migrations.RenameModel(
            old_name='trainerreg',
            new_name='trainer',
        ),
        migrations.RenameModel(
            old_name='userreg',
            new_name='user',
        ),
    ]
