# Generated by Django 5.2.7 on 2025-11-15 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_dive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dive',
            old_name='dive',
            new_name='dive_book',
        ),
    ]
