# Generated by Django 5.2.7 on 2025-11-18 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_dive_dive_dive_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dive',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='dive_book',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dive',
            name='name',
        ),
        migrations.AddField(
            model_name='dive',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dive',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
