# Generated by Django 5.2.7 on 2025-11-19 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_dive_contact_remove_dive_dive_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AddField(
            model_name='dive',
            name='places',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.place'),
        ),
    ]
