# Generated by Django 5.2.7 on 2025-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_dive_categorys_dive_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='status',
            field=models.CharField(default='pending'),
        ),
    ]
