# Generated by Django 5.2.7 on 2025-11-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='trainer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trainer'),
        ),
    ]
