# Generated by Django 5.2.7 on 2025-11-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_dive_trainer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dive',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DiveMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('experience_level', models.CharField(max_length=50)),
                ('emergency_name', models.CharField(max_length=150)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('conditions', models.TextField(blank=True)),
                ('medical_details', models.TextField(blank=True)),
                ('physician', models.CharField(blank=True, max_length=150)),
                ('recent_dive', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_forms', to='app.dive')),
            ],
        ),
    ]
